services:
  application:
    image: mini:latest
    restart: always
    build:
      context: ../
      dockerfile: ./build/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db
      - redis
      - llm
    links:
      - db
      - redis
      - llm
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    networks:
      - app-network
    environment:
      - MYSQL_DATABASE=mySql
      - MYSQL_ROOT_PASSWORD=password
  llm:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge